# Configuracion de Spring
spring:
  #Nombre del modulo
  application:
    name : microservicio.documents
  # Configuracion para la conexion a la base de datos
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  # Configuracion para recibir archivos multimedia
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


